Fix undeclared 'IPAHAL_NAT_INVALID_PROTOCOL'
FAILED: target  C: libipanat <= vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drvi.c
Outputs: out/target/product/ali/obj/SHARED_LIBRARIES/libipanat_intermediates/ipa_nat_drvi.o
Error: exited with code: 1
Command: /bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang  -I device/motorola/ali/include -I vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src/../inc -I vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src -I out/target/product/ali/obj/SHARED_LIBRARIES/libipanat_intermediates -I out/target/product/ali/gen/SHARED_LIBRARIES/libipanat_intermediates \$(cat out/target/product/ali/obj/SHARED_LIBRARIES/libipanat_intermediates/import_includes)   -isystem out/target/product/ali/obj/include -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin   -std=gnu99    -Wall -Werror -DFEATURE_IPA_ANDROID -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/target/product/ali/obj/SHARED_LIBRARIES/libipanat_intermediates/ipa_nat_drvi.d -o out/target/product/ali/obj/SHARED_LIBRARIES/libipanat_intermediates/ipa_nat_drvi.o vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drvi.c"
Output:
 [1mvendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drvi.c:2205:25:  [0m [0;1;31merror:  [0m [1muse of undeclared identifier 'IPAHAL_NAT_INVALID_PROTOCOL' [0m
                                        PROTOCOL_FIELD) == IPAHAL_NAT_INVALID_PROTOCOL
 [0;1;32m                                                           ^
 [0m1 error generated.